fint:
  application-id: fint-flyt-value-converting-service
server:
  error:
    include-message: always
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-resource-server
      - flyt-postgres